//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>
//
// <copyright file="IRoleModulePermissionService.cs">
//		Copyright(c)2013 QuickFramework.All rights reserved.
//		开发组织：QuickFramework
//		公司网站：QuickFramework
//		所属工程：Business.Service
//		生成时间：2013-12-11 23:55
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections.Generic;

using Core.Tool;
using Domain.Repository.Authen;
using Domain.DB.Models.Authen;
using Domain.Site.Models.Authen.Permission;
using Domain.Site.Models.Authen.RoleModulePermission;
using Domain.Site.Models.SSO;

namespace Business.Service.Authen
{
	/// <summary>
    /// 服务层接口 —— IRoleModulePermissionService
    /// </summary>
	public interface IResourcesService
    {
        #region 属性

		IQueryable<Resources> Resourcess { get; }

        #endregion

        #region 公共方法

        OperationResult SetResources( IEnumerable<ResourcesModel> addResourcesList, IEnumerable<ResourcesModel> removeResourcesList);

        List<SubSystem> GetSubUser(User UserModel, int RType);

        List<int> GetSystemUserIds(int SystemId);
        #endregion
    }
}
