//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>
//
// <copyright file="IModulePermissionRepository.generated.cs">
//		Copyright(c)2013 PubSerFramework.All rights reserved.
//		开发组织：PubSerFramework
//		公司网站：PubSerFramework
//		所属工程：Domain.Repository
//		生成时间：2017-11-15 17:06
// </copyright>
//------------------------------------------------------------------------------

using System;

using Core.EFData;
using Domain.DB.Models.System;


namespace Domain.Repository.System
{
	/// <summary>
    /// 仓储操作层接口 —— ModulePermission
    /// </summary>
    public interface IModulePermissionRepository : IRepository<ModulePermission, Int32>
    { }
}
