//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>
//
// <copyright file="ModulePermissionPermissionService.cs">
//		Copyright(c)2013 QuickFramework.All rights reserved.
//		开发组织：QuickFramework
//		公司网站：QuickFramework
//		所属工程：Business.Service
//		生成时间：2013-12-11 23:55
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.Composition;
using System.Linq;
using Domain.DB.Models.System;
using Core.Tool;
using System.Collections.Generic;
using Domain.Site.Models.AdminCommon;

namespace Business.Service.System.Impl
{
	/// <summary>
    /// 服务层实现 —— ModulePermissionService
    /// </summary>
    [Export(typeof(ILocationService))]
    public class ModulePermissionService : CoreServiceBase, ILocationService
	{
		#region 属性

		[Import]
        public IModulePermissionRepository ModulePermissionRepository { get; set; }

        public IQueryable<ModulePermission> ModulePermissions
        {
            get { return ModulePermissionRepository.Entities; }
        }

		#endregion

		#region 公共方法

		public OperationResult SetButton(ButtonModel model)
        {
			#region Add & Update 
			var oldDataList = ModulePermissions.Where(t => t.ModuleId == model.ModuleId && t.IsDeleted == false).Select(t => t.PermissionId);
			var newDataList = model.SelectedButtonList.ToList();
			var intersectIds = oldDataList.Intersect(newDataList).ToList(); // Same Ids
			var updateIds = oldDataList.Except(intersectIds).ToList(); // Remove Ids
			var addIds = newDataList.Except(oldDataList).ToList(); // Add Ids
			//逻辑删除
			foreach (var removeId in updateIds)
			{
				var updateEntity = ModulePermissions.FirstOrDefault(t => t.ModuleId == model.ModuleId && t.PermissionId == removeId && t.IsDeleted == false);
				if (updateEntity != null)
				{
					updateEntity.IsDeleted = true;
					ModulePermissionRepository.Update(updateEntity);
				}
				
			}
			//插入 & 更新
			foreach (var addId in addIds)
			{
				var updateEntity = ModulePermissions.FirstOrDefault(t => t.ModuleId == model.ModuleId && t.PermissionId == addId && t.IsDeleted == true);
				if (updateEntity != null)
				{
					updateEntity.IsDeleted = false;
                    updateEntity.CreateTime = DateTime.Now;
                    ModulePermissionRepository.Update(updateEntity);
				}
				else
				{
					var addEntity = new ModulePermission { ModuleId = model.ModuleId, PermissionId = addId };
					ModulePermissionRepository.Insert(addEntity);
				}			
			}
			#endregion

            return new OperationResult(OperationResultType.Success, "设置成功");
		}

		#endregion
	}
}
